### ISSUE TITLE
Edit this page links don't work

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/anarchy-ai.github.io#1]
https://anarchy-ai.github.io/docs/documentation/Careers

**Comment by AryPathania** [comment]
Hey, the links seem to be working for me. Do you know which ones specifically were giving you trouble?

**Comment by mmirman** [comment]
well now they are gone o.O

**Comment by AryPathania** [comment]
Added back and fixed the links :). The problem was with the routing. The base link needed to be 'https://github.com/anarchy-ai/anarchy-ai.github.io/tree/main/' and then docusaurus appends the page path to the url according to it's location in the file. It was getting tripped up since there were two branches.
